# SPDX-FileCopyrightText: 2020 The insulin-reminder Authors
#
# SPDX-License-Identifier: MIT

[tool.black]
line-length = 88
target-version = ['py37']

[tool.isort]
# These settings ensure that black and isort don't disagree on the imports.
line_length = 88
multi_line_output = 3
include_trailing_comma = true

known_circuitpython = ["board", "busio", "digitalio", "supervisor"]
known_third_party = ["adafruit_esp32spi", "adafruit_mcp230xx", "adafruit_requests", "adafruit_rgbled", "neopixel"]
sections = "FUTURE,STDLIB,CIRCUITPYTHON,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
